Revert "Remove collective.indexing"
This reverts commit e342f96805af8cc59423e3aaeef9b07c253e08aa.
Reason: this results in
AttributeError: type object 'IPortalCatalogQueueProcessor' has no attribute '__iro__'
AttributeError: type object 'IIndexingConfig' has no attribute '__iro__'

We need to properly handle removal of c.indexing